### ISSUE TITLE
json.Marshal can't decode arrays: "invalid key to 'next'"

### ISSUE THREAD

**Issue by amomchilov** [Shopify/goluago#31]
Lua's `table` type models both "arrays" like `{ 1, 2, 3 }` (accessed by index) and "dictionaries" like `{ a = 1, b = 2, c = 3}` (accessed by key).

# Issue

[json.mashal](https://github.com/Shopify/goluago/blob/9f09792eea6caa4980eefc19dee971505e74fe78/pkg/encoding/json/json.go#L31) can handle decoding a `table` like a dictionary, but it fails to decode a table like an array, printing the error `invalid key to 'next'`.

Here's a simple reproducible example:

```lua
payload = {
   a_key = { 1, 2, 3 } -- the value is a table, but it's meant to be json-encoded as an array.
}
json.marshal(payload) -- 💥 `invalid key to 'next'`
```

# Goal

Teach `json.marshal` to [detect tables that are intended to model arrays](https://stackoverflow.com/q/7526223/3141234), and decode them into the appropriate `[1, 2, 3]` JSON form.

# Workaround

<strike>It ain't pretty:

```lua
local changeset = '['
      .. table.concat({
        json.marshal(config.add_variant_change),
        json.marshal(config.add_shipping_line_change),
      }, ",")
  .. ']'
```
</strike>

**Comment by joeytepp** [comment]
The following code should work
```lua
payload = {
   a_key = array({ 1, 2, 3 })
}
```

**Comment by fbogsany** [comment]
This happens because we rely on an "array" marker to efficiently identify the table as an array: https://github.com/Shopify/goluago/blob/9f09792eea6caa4980eefc19dee971505e74fe78/util/deep_pull.go#L56-L58

**Comment by amomchilov** [comment]
Thanks Joey, that works.

@fbogsany It looks like this Lua function can detect arrays in `O(1)`, without needing to remember to tag them with a marker:

```Lua
function is_array(tbl)
  return type(tbl) == 'table' and (#tbl > 0 or next(tbl) == nil)
end
```

This could be converted to go and be used by the JSON utilities. I'm curious how the performance compares.

The `array` function call works, but it's not very discoverable.

**Comment by fbogsany** [comment]
@amomchilov unfortunately, that isn't `O(1)`. The length operator (`#tbl` in your example) is `O(log n)` where `n` is the largest natural key in the table: https://www.lua.org/manual/5.4/manual.html#3.4.7

**Comment by amomchilov** [comment]
Interesting!

Do you think that might be prohibitively expensive, though I'm not sure.

I wonder if there are anyways to increase the discoverability of the `array` function.

**Comment by joeytepp** [comment]
Closing this as a solution was found.
